spring.application.name=asgard
server.port=8082

app.cors.allowed-origin=http://localhost:4200

spring.datasource.url=jdbc:postgresql://localhost:5432/asgard
spring.datasource.username=postgres
spring.datasource.password=admin

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
sqping.jpa.properties.hibernate.format_sql=true

jwt.secret=a465a0a165a7ffcb391050bcabc48ececc628ff91cf96a64f2b0ab6ae005a8561803edf532003f26960ef822e404d15e6dd2fbea46f704e4ac37a1b5135d8cd1
jwt.expiration=86400000

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true